// Example demonstrating custom encoding/decoding hooks
// This example shows validation, transformation, and encryption use cases

using System;
using System.Runtime.InteropServices;

namespace CustomEncodingHooksExample
{
    // Example 1: Simple Validation Hooks
    public class ValidationExample
    {
        public static void Run()
        {
            Console.WriteLine("=== Validation Example ===");
            
            // Create hooks with validation
            var hooks = new EncodingHooks<TradeData>
            {
                PreEncoding = (ref TradeData trade) =>
                {
                    // Validate before encoding
                    if (trade.Price <= 0)
                    {
                        Console.WriteLine($"Invalid price: {trade.Price}");
                        return false;
                    }
                    if (trade.Quantity <= 0)
                    {
                        Console.WriteLine($"Invalid quantity: {trade.Quantity}");
                        return false;
                    }
                    return true;
                },
                PostDecoding = (ref TradeData trade) =>
                {
                    // Validate after decoding
                    if (trade.Price <= 0 || trade.Quantity <= 0)
                    {
                        Console.WriteLine("Decoded trade has invalid values");
                        return false;
                    }
                    Console.WriteLine($"Trade validated: Price={trade.Price}, Qty={trade.Quantity}");
                    return true;
                }
            };

            // Example usage would go here
            Console.WriteLine("Validation hooks configured successfully");
        }
    }

    // Example 2: Reusable Hooks Pattern
    public static class TradeHooks
    {
        // Cache hook instances for performance
        private static readonly EncodingHooks<TradeData> _validationHooks = new()
        {
            PreEncoding = ValidateBeforeEncode,
            PostDecoding = ValidateAfterDecode
        };

        public static EncodingHooks<TradeData> Validation => _validationHooks;

        private static bool ValidateBeforeEncode(ref TradeData trade)
        {
            if (trade.Price <= 0 || trade.Price > 1000000)
                return false;
            if (trade.Quantity <= 0 || trade.Quantity > 1000000)
                return false;
            
            // Normalize
            trade.Price = Math.Round(trade.Price, 2);
            return true;
        }

        private static bool ValidateAfterDecode(ref TradeData trade)
        {
            // Validate ranges
            return trade.Price > 0 && trade.Quantity > 0;
        }
    }

    // Demo message structure (would be generated by SBE generator)
    [StructLayout(LayoutKind.Explicit, Pack = 1)]
    public struct TradeData
    {
        public const int MESSAGE_SIZE = 32;
        [FieldOffset(0)] public long TradeId;
        [FieldOffset(8)] public decimal Price;
        [FieldOffset(24)] public int Quantity;
    }

    // Stub classes for compilation (would be generated)
    public class EncodingHooks<T> where T : struct
    {
        public MessagePreEncodingHook<T>? PreEncoding { get; set; }
        public MessagePostEncodingHook<T>? PostDecoding { get; set; }
    }

    public delegate bool MessagePreEncodingHook<T>(ref T message) where T : struct;
    public delegate bool MessagePostEncodingHook<T>(ref T message) where T : struct;
}
