using Microsoft.CodeAnalysis;
using SbeSourceGenerator.Schema;
using System.Collections.Generic;
using System.Text;

namespace SbeSourceGenerator.Generators
{
    /// <summary>
    /// Issue #147: emits a per-schema zero-cost dispatcher that decodes the message header
    /// and routes to a strongly-typed handler. The handler is a generic <c>struct</c> implementing
    /// <c>ISbeMessageHandler</c>, which lets the JIT specialize each <c>Dispatch&lt;T&gt;</c>
    /// instantiation and devirtualize the call (no virtual indirection at runtime).
    /// </summary>
    internal class DispatcherGenerator : ICodeGenerator
    {
        public IEnumerable<(string name, string content)> Generate(string ns, ParsedSchema schema, SchemaContext context, SourceProductionContext sourceContext)
        {
            if (schema.Messages == null || schema.Messages.Count == 0)
                yield break;

            // The dispatcher and interface live in the canonical V0 namespace where {Msg}Data structs reside.
            var baseNs = ns;

            string headerTypeName = "MessageHeader";
            if (context.GeneratedTypeNames.TryGetValue(context.HeaderType, out var resolvedHeaderName))
                headerTypeName = resolvedHeaderName;

            // Resolve each message's generated type name (already registered by MessagesCodeGenerator).
            var messages = new List<(string GeneratedName, int TemplateId)>(schema.Messages.Count);
            foreach (var m in schema.Messages)
            {
                if (!context.GeneratedTypeNames.TryGetValue(m.Name, out var generatedName))
                    generatedName = TypeTranslator.NormalizeName(m.Name);
                if (!int.TryParse(m.Id, out var templateId))
                    continue;
                messages.Add((generatedName, templateId));
            }

            if (messages.Count == 0)
                yield break;

            // ---- ISbeMessageHandler interface ----
            var sb = new StringBuilder(1024);
            sb.AppendLine("// <auto-generated />");
            sb.Append("namespace ").Append(baseNs).AppendLine(";");
            sb.AppendLine();
            sb.AppendLine("/// <summary>Handler interface dispatched to by <see cref=\"SbeDispatcher\"/>. Implement as a <c>struct</c> for zero-cost devirtualized dispatch.</summary>");
            sb.AppendLine("public interface ISbeMessageHandler");
            sb.AppendLine("{");
            foreach (var (name, _) in messages)
            {
                sb.Append("\t/// <summary>Invoked when a <c>").Append(name).AppendLine("</c> message is dispatched.</summary>");
                sb.Append("\tvoid On").Append(name).Append("(in ").Append(name).AppendLine("DataReader reader, int blockLength, int version);");
            }
            sb.Append("\t/// <summary>Invoked when an unknown templateId is encountered.</summary>");
            sb.AppendLine();
            sb.AppendLine("\tvoid OnUnknownMessage(int templateId, int blockLength, int version, System.ReadOnlySpan<byte> payload);");
            sb.AppendLine("}");

            yield return (context.CreateHintName(baseNs, "Dispatcher", "ISbeMessageHandler"), sb.ToString());

            // ---- SbeDispatcher static class ----
            sb.Clear();
            sb.AppendLine("// <auto-generated />");
            sb.Append("namespace ").Append(baseNs).AppendLine(";");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Issue #147: zero-cost message dispatcher. Reads the SBE message header from the buffer,");
            sb.AppendLine("/// then routes to the appropriate <c>On{Msg}</c> method on <typeparamref name=\"T\"/> based on <c>TemplateId</c>.");
            sb.AppendLine("/// Because <typeparamref name=\"T\"/> is constrained to <c>struct, ISbeMessageHandler</c>, the JIT");
            sb.AppendLine("/// generates a specialized version per handler type and devirtualizes every dispatch call.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("public static class SbeDispatcher");
            sb.AppendLine("{");
            sb.AppendLine("\t/// <summary>Decodes the header at the start of <paramref name=\"buffer\"/> and dispatches to the matching handler method.</summary>");
            sb.AppendLine("\t/// <returns><c>true</c> if a known message was dispatched; <c>false</c> if the header could not be read or the templateId is unknown (in which case <c>OnUnknownMessage</c> is called).</returns>");
            sb.AppendLine("\t[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.Append("\tpublic static bool Dispatch<T>(System.ReadOnlySpan<byte> buffer, ref T handler) where T : struct, ISbeMessageHandler");
            sb.AppendLine();
            sb.AppendLine("\t{");
            sb.Append("\t\tif (!").Append(headerTypeName).AppendLine(".TryParse(buffer, out var header, out var payload))");
            sb.AppendLine("\t\t\treturn false;");
            sb.AppendLine();
            sb.AppendLine("\t\tint templateId = header.TemplateId;");
            sb.AppendLine("\t\tint blockLength = header.BlockLength;");
            sb.AppendLine("\t\tint version = header.Version;");
            sb.AppendLine();
            sb.AppendLine("\t\tswitch (templateId)");
            sb.AppendLine("\t\t{");
            foreach (var (name, templateId) in messages)
            {
                sb.Append("\t\t\tcase ").Append(templateId).AppendLine(":");
                sb.AppendLine("\t\t\t{");
                sb.Append("\t\t\t\tif (!").Append(name).AppendLine("Data.TryParse(payload, blockLength, out var reader))");
                sb.AppendLine("\t\t\t\t\treturn false;");
                sb.Append("\t\t\t\thandler.On").Append(name).AppendLine("(in reader, blockLength, version);");
                sb.AppendLine("\t\t\t\treturn true;");
                sb.AppendLine("\t\t\t}");
            }
            sb.AppendLine("\t\t\tdefault:");
            sb.AppendLine("\t\t\t\thandler.OnUnknownMessage(templateId, blockLength, version, payload);");
            sb.AppendLine("\t\t\t\treturn false;");
            sb.AppendLine("\t\t}");
            sb.AppendLine("\t}");
            sb.AppendLine("}");

            yield return (context.CreateHintName(baseNs, "Dispatcher", "SbeDispatcher"), sb.ToString());
        }
    }
}
