namespace SbeSourceGenerator.SemanticTypes
{
    /// <summary>
    /// Issue #166: source emitted into every consumer assembly via
    /// <c>RegisterPostInitializationOutput</c>. Defines the assembly-attribute,
    /// the converter interface, and the built-in FIX-style converters in a
    /// stable namespace so that user <c>[assembly: SbeSemanticType(...)]</c>
    /// declarations always have something to point at, regardless of schema
    /// processing order.
    /// </summary>
    internal static class SemanticTypesRuntimeSource
    {
        public const string HintName = "SbeSourceGenerator.Runtime.SemanticTypes.g.cs";

        public const string Source = @"// <auto-generated />
// Issue #166: declarative semantic-type registry runtime types.
// This file is emitted by SbeSourceGenerator into every consumer compilation.
// Requires C# 11 / .NET 7+ (uses static abstract interface members).
#nullable enable
namespace SbeSourceGenerator.Runtime
{
    using System;

    /// <summary>
    /// Registers a converter that produces a typed accessor (e.g. <see cref=""DateTime""/>,
    /// <see cref=""DateOnly""/>) alongside the raw wire accessor for any field whose
    /// schema <c>semanticType</c> attribute equals <see cref=""SemanticType""/>. The generator
    /// auto-registers a built-in set (UTCTimestamp variants, UTCDateOnly, LocalMktDate,
    /// UTCTimeOnly, MonthYear); user registrations override built-ins for the same key.
    /// </summary>
    [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
    internal sealed class SbeSemanticTypeAttribute : Attribute
    {
        public string SemanticType { get; }
        public Type Converter { get; }
        public SbeSemanticTypeAttribute(string semanticType, Type converter)
        {
            SemanticType = semanticType;
            Converter = converter;
        }
    }

    /// <summary>
    /// Implement on a <c>static</c> class to register a typed accessor for an SBE wire primitive.
    /// The generator inspects the <c>TWire</c> generic argument to validate it matches the field's
    /// primitive type (mismatch → SBE016 error).
    /// </summary>
    internal interface ISbeSemanticConverter<TWire, TSemantic> where TWire : unmanaged
    {
        static abstract TSemantic FromWire(TWire wire);
        static abstract TWire ToWire(TSemantic semantic);
    }

    // -------- Built-in converters --------
    // Naming mirrors common FIX semanticType values. Generated code calls these as
    // concrete static methods (no virtual dispatch, AOT-friendly).

    internal static class UtcTimestampNanosConverter
    {
        // DateTime ticks are 100ns. Nanosecond inputs are truncated to the nearest 100ns boundary.
        public static DateTime FromWire(ulong wire) =>
            new DateTime(DateTime.UnixEpoch.Ticks + (long)(wire / 100UL), DateTimeKind.Utc);
        public static ulong ToWire(DateTime semantic) =>
            (ulong)((semantic.ToUniversalTime().Ticks - DateTime.UnixEpoch.Ticks) * 100L);
    }

    internal static class UtcTimestampMicrosConverter
    {
        public static DateTime FromWire(ulong wire) =>
            new DateTime(DateTime.UnixEpoch.Ticks + (long)(wire * 10UL), DateTimeKind.Utc);
        public static ulong ToWire(DateTime semantic) =>
            (ulong)((semantic.ToUniversalTime().Ticks - DateTime.UnixEpoch.Ticks) / 10L);
    }

    internal static class UtcTimestampMillisConverter
    {
        public static DateTime FromWire(ulong wire) =>
            DateTime.UnixEpoch.AddMilliseconds(wire);
        public static ulong ToWire(DateTime semantic) =>
            (ulong)(semantic.ToUniversalTime() - DateTime.UnixEpoch).TotalMilliseconds;
    }

    internal static class UtcTimestampSecondsConverter
    {
        public static DateTime FromWire(ulong wire) =>
            DateTime.UnixEpoch.AddSeconds(wire);
        public static ulong ToWire(DateTime semantic) =>
            (ulong)(semantic.ToUniversalTime() - DateTime.UnixEpoch).TotalSeconds;
    }

    internal static class UtcDateOnlyConverter
    {
        private static readonly DateOnly Epoch = new DateOnly(1970, 1, 1);
        public static DateOnly FromWire(ushort wire) => Epoch.AddDays(wire);
        public static ushort ToWire(DateOnly semantic) => checked((ushort)(semantic.DayNumber - Epoch.DayNumber));
    }

    internal static class LocalMktDateConverter
    {
        private static readonly DateOnly Epoch = new DateOnly(1970, 1, 1);
        public static DateOnly FromWire(ushort wire) => Epoch.AddDays(wire);
        public static ushort ToWire(DateOnly semantic) => checked((ushort)(semantic.DayNumber - Epoch.DayNumber));
    }

    internal static class UtcTimeOnlyNanosConverter
    {
        public static TimeOnly FromWire(ulong wire) => new TimeOnly((long)(wire / 100UL));
        public static ulong ToWire(TimeOnly semantic) => (ulong)(semantic.Ticks * 100L);
    }

    internal static class MonthYearConverter
    {
        public static (int Year, int Month) FromWire(uint wire) => ((int)(wire / 100u), (int)(wire % 100u));
        public static uint ToWire((int Year, int Month) semantic) => checked((uint)(semantic.Year * 100 + semantic.Month));
    }
}
";
    }
}
