using System;
using System.Runtime.InteropServices;
using Integration.Test;

namespace SbeCodeGenerator.IntegrationTests
{
    /// <summary>
    /// Integration tests that validate the source generator works end-to-end:
    /// - XML schemas are fed via AdditionalFiles
    /// - Code is generated by the SBE source generator
    /// - Generated code compiles successfully
    /// - Generated code can be instantiated and used
    /// These tests ensure the generator output is valid and usable in real scenarios.
    /// </summary>
    public class GeneratorIntegrationTests
    {
        [Fact]
        public void GeneratedCode_CompilesSuccessfully()
        {
            // This test validates that code was generated and compiles by referencing types
            // If the generator didn't work, these types wouldn't exist and the test wouldn't compile
            
            // Verify types from integration-test-schema.xml are generated
            Assert.NotNull(typeof(Integration.Test.OrderSide));
            Assert.NotNull(typeof(Integration.Test.OrderType));
            Assert.NotNull(typeof(Integration.Test.MessageHeader));
            Assert.NotNull(typeof(Integration.Test.NewOrderData));
            Assert.NotNull(typeof(Integration.Test.OrderBookData));
        }

        [Fact]
        public void GeneratedEnum_CanBeUsedInCode()
        {
            // Verify enums can be instantiated and used
            var orderSide = Integration.Test.OrderSide.Buy;
            Assert.Equal((byte)1, (byte)orderSide);
            
            var orderType = Integration.Test.OrderType.Limit;
            Assert.Equal((byte)2, (byte)orderType);
        }

        [Fact]
        public unsafe void GeneratedMessage_CanBeInstantiatedAndAccessed()
        {
            // Verify we can create and access generated message structures
            // Verify the struct has the expected size (calculated based on fields)
            Assert.True(Marshal.SizeOf<Integration.Test.NewOrderData>() > 0);
            
            // Verify we can set and get fields through the generated properties
            Span<byte> buffer = stackalloc byte[1024];
            ref Integration.Test.NewOrderData orderRef = ref MemoryMarshal.AsRef<Integration.Test.NewOrderData>(buffer);
            
            // Use implicit conversions and constructors
            orderRef.OrderId = 123456;  // Implicit conversion from long
            orderRef.Price = 100000;    // Implicit conversion from long
            orderRef.Quantity = 500;
            orderRef.Side = Integration.Test.OrderSide.Buy;
            orderRef.OrderType = Integration.Test.OrderType.Limit;
            
            Assert.Equal(123456, orderRef.OrderId.Value);
            Assert.Equal(100000, orderRef.Price.Value);
            Assert.Equal(500, orderRef.Quantity);
            Assert.Equal(Integration.Test.OrderSide.Buy, orderRef.Side);
            Assert.Equal(Integration.Test.OrderType.Limit, orderRef.OrderType);
        }

        [Fact]
        public unsafe void GeneratedMessageHeader_HasCorrectStructure()
        {
            // Verify MessageHeader composite is generated correctly
            Span<byte> buffer = stackalloc byte[128];
            ref Integration.Test.MessageHeader header = ref MemoryMarshal.AsRef<Integration.Test.MessageHeader>(buffer);
            
            header.BlockLength = 100;
            header.TemplateId = 10;
            header.SchemaId = 2;
            header.Version = 0;
            
            Assert.Equal((ushort)100, header.BlockLength);
            Assert.Equal((ushort)10, header.TemplateId);
            Assert.Equal((ushort)2, header.SchemaId);
            Assert.Equal((ushort)0, header.Version);
        }


        [Fact]
        public void GeneratedMessage_TryParseReturnsStructCopy()
        {
            // Prepare a buffer with the raw bytes of NewOrderData
            Span<byte> buffer = stackalloc byte[Integration.Test.NewOrderData.MESSAGE_SIZE];
            ref Integration.Test.NewOrderData orderRef = ref MemoryMarshal.AsRef<Integration.Test.NewOrderData>(buffer);
            orderRef.OrderId = 999;      // Implicit conversion
            orderRef.Price = 50000;      // Implicit conversion
            orderRef.Quantity = 100;
            orderRef.Side = Integration.Test.OrderSide.Sell;
            orderRef.OrderType = Integration.Test.OrderType.Market;

            // Act
            var success = Integration.Test.NewOrderData.TryParse(buffer, out var parsedOrder, out var variableData);

            // Assert
            Assert.True(success);
            Assert.Equal(0, variableData.Length);
            Assert.Equal(999, parsedOrder.OrderId.Value);
            Assert.Equal(50000, parsedOrder.Price.Value);
            Assert.Equal(100, parsedOrder.Quantity);
            Assert.Equal(Integration.Test.OrderSide.Sell, parsedOrder.Side);
            Assert.Equal(Integration.Test.OrderType.Market, parsedOrder.OrderType);
        }

        [Fact]
        public void GeneratedMessageHeader_TryParseExposesPayload()
        {
            Span<byte> buffer = stackalloc byte[Integration.Test.MessageHeader.MESSAGE_SIZE + Integration.Test.NewOrderData.MESSAGE_SIZE];
            var bodyOffset = Integration.Test.MessageHeader.MESSAGE_SIZE;
            ref Integration.Test.MessageHeader header = ref MemoryMarshal.AsRef<Integration.Test.MessageHeader>(buffer);
            header.BlockLength = (ushort)Integration.Test.NewOrderData.MESSAGE_SIZE;
            header.TemplateId = (ushort)Integration.Test.NewOrderData.MESSAGE_ID;
            header.SchemaId = 2;
            header.Version = 0;
            ref Integration.Test.NewOrderData order = ref MemoryMarshal.AsRef<Integration.Test.NewOrderData>(buffer.Slice(bodyOffset));
            order.OrderId = 42;  // Implicit conversion

            var success = Integration.Test.MessageHeader.TryParse(buffer, out var parsedHeader, out var payload);

            Assert.True(success);
            Assert.Equal(Integration.Test.NewOrderData.MESSAGE_ID, parsedHeader.TemplateId);
            Assert.Equal(Integration.Test.NewOrderData.MESSAGE_SIZE, parsedHeader.BlockLength);
            Assert.Equal(Integration.Test.NewOrderData.MESSAGE_SIZE, payload.Length);
            Assert.Equal(42, MemoryMarshal.AsRef<Integration.Test.NewOrderData>(payload).OrderId.Value);
        }

        [Fact]
        public void GeneratedUtilities_NumberExtensionsExist()
        {
            // Verify NumberExtensions utility class is generated
            Assert.NotNull(typeof(Integration.Test.NumberExtensions));
        }

        [Fact]
        public void GeneratedCode_HasCorrectNamespaces()
        {
            // Verify namespace generation from file names
            // integration-test-schema.xml -> Integration.Test
            Assert.Equal("Integration.Test", typeof(Integration.Test.OrderSide).Namespace);
        }

        [Fact]
        public unsafe void GeneratedMessageWithGroups_CanBeAccessed()
        {
            // Verify messages with groups are generated (OrderBook has bids/asks groups)
            Assert.True(Marshal.SizeOf<Integration.Test.OrderBookData>() > 0);
            
            Span<byte> buffer = stackalloc byte[1024];
            ref Integration.Test.OrderBookData bookRef = ref MemoryMarshal.AsRef<Integration.Test.OrderBookData>(buffer);
            
            bookRef.InstrumentId = 42;
            Assert.Equal(42, bookRef.InstrumentId);
        }

        [Fact]
        public void BlockLengthExtension_AllowsDifferentBlockLengths()
        {
            // Test the new TryParse overload that accepts a blockLength parameter
            // This is the foundation for schema evolution support
            
            Span<byte> buffer = stackalloc byte[Integration.Test.NewOrderData.MESSAGE_SIZE + 32]; // Extra space
            ref Integration.Test.NewOrderData message = ref MemoryMarshal.AsRef<Integration.Test.NewOrderData>(buffer);
            
            message.OrderId = 123;    // Implicit conversion
            message.Price = 9950;     // Implicit conversion
            message.Quantity = 100;
            message.Side = Integration.Test.OrderSide.Buy;
            message.OrderType = Integration.Test.OrderType.Limit;
            
            // Test with exact block length (standard case)
            var success1 = Integration.Test.NewOrderData.TryParse(
                buffer, 
                Integration.Test.NewOrderData.MESSAGE_SIZE, 
                out var parsedMsg1, 
                out var remaining1);
            
            Assert.True(success1);
            Assert.Equal(123, parsedMsg1.OrderId.Value);
            Assert.Equal(32, remaining1.Length); // 32 bytes remain for variable data
            
            // Test with larger block length (simulates newer schema with additional fields)
            int extendedBlockLength = Integration.Test.NewOrderData.MESSAGE_SIZE + 16;
            var success2 = Integration.Test.NewOrderData.TryParse(
                buffer, 
                extendedBlockLength, 
                out var parsedMsg2, 
                out var remaining2);
            
            Assert.True(success2);
            Assert.Equal(123, parsedMsg2.OrderId.Value);
            Assert.Equal(16, remaining2.Length); // 16 bytes remain for variable data
            
            // Test with smaller block length (simulates older schema with fewer fields)
            int smallerBlockLength = Integration.Test.NewOrderData.MESSAGE_SIZE - 2;
            var success3 = Integration.Test.NewOrderData.TryParse(
                buffer, 
                smallerBlockLength, 
                out var parsedMsg3, 
                out var remaining3);
            
            Assert.True(success3);
            Assert.Equal(123, parsedMsg3.OrderId.Value);
            Assert.Equal(34, remaining3.Length); // More bytes remain
        }

        [Fact]
        public void BlockLengthExtension_BackwardCompatibleTryParse()
        {
            // Verify that the original TryParse (without blockLength) still works
            // This ensures backward compatibility with existing code
            
            Span<byte> buffer = stackalloc byte[Integration.Test.NewOrderData.MESSAGE_SIZE];
            ref Integration.Test.NewOrderData message = ref MemoryMarshal.AsRef<Integration.Test.NewOrderData>(buffer);
            
            message.OrderId = 456;    // Implicit conversion
            message.Price = 10050;    // Implicit conversion
            
            // Use the original TryParse method (calls the new one internally with MESSAGE_SIZE)
            var success = Integration.Test.NewOrderData.TryParse(buffer, out var parsedMsg, out var remaining);
            
            Assert.True(success);
            Assert.Equal(456, parsedMsg.OrderId.Value);
            Assert.Equal(10050, parsedMsg.Price.Value);
            Assert.Equal(0, remaining.Length);
        }

        [Fact]
        public void ValidationExtensions_ValidatePrice_ThrowsOnNegativeValue()
        {
            // Arrange
            Integration.Test.Price price = -100;  // Implicit conversion

            // Act & Assert
            var exception = Assert.Throws<ArgumentOutOfRangeException>(() => price.Validate());
            Assert.Contains("Price must be greater than or equal to 0", exception.Message);
        }

        [Fact]
        public void ValidationExtensions_ValidatePrice_PassesOnValidValue()
        {
            // Arrange
            Integration.Test.Price price = 1000;  // Implicit conversion

            // Act & Assert (should not throw)
            price.Validate();
        }

        [Fact]
        public void ValidationExtensions_ValidateOrderId_ThrowsOnZeroValue()
        {
            // Arrange
            Integration.Test.OrderId orderId = 0;  // Implicit conversion

            // Act & Assert
            var exception = Assert.Throws<ArgumentOutOfRangeException>(() => orderId.Validate());
            Assert.Contains("OrderId must be greater than or equal to 1", exception.Message);
        }

        [Fact]
        public void ValidationExtensions_ValidateOrderId_PassesOnValidValue()
        {
            // Arrange
            Integration.Test.OrderId orderId = 123;  // Implicit conversion

            // Act & Assert (should not throw)
            orderId.Validate();
        }

        [Fact]
        public void ValidationExtensions_TryValidatePrice_ReturnsFalseOnNegativeValue()
        {
            // Arrange
            Integration.Test.Price price = -100;  // Implicit conversion

            // Act
            bool result = price.TryValidate(out string? errorMessage);

            // Assert
            Assert.False(result);
            Assert.NotNull(errorMessage);
            Assert.Contains("Price must be greater than or equal to 0", errorMessage);
            Assert.Contains("-100", errorMessage);
        }

        [Fact]
        public void ValidationExtensions_TryValidatePrice_ReturnsTrueOnValidValue()
        {
            // Arrange
            Integration.Test.Price price = 1000;  // Implicit conversion

            // Act
            bool result = price.TryValidate(out string? errorMessage);

            // Assert
            Assert.True(result);
            Assert.Null(errorMessage);
        }

        [Fact]
        public void ValidationExtensions_TryValidateOrderId_ReturnsFalseOnZeroValue()
        {
            // Arrange
            Integration.Test.OrderId orderId = 0;  // Implicit conversion

            // Act
            bool result = orderId.TryValidate(out string? errorMessage);

            // Assert
            Assert.False(result);
            Assert.NotNull(errorMessage);
            Assert.Contains("OrderId must be greater than or equal to 1", errorMessage);
        }

        [Fact]
        public void ValidationExtensions_CreateValidatedPrice_ReturnsValueOnValid()
        {
            // Arrange
            Integration.Test.Price price = 1000;  // Implicit conversion

            // Act
            var validatedPrice = price.CreateValidated();

            // Assert
            Assert.Equal(1000, validatedPrice.Value);
        }

        [Fact]
        public void ValidationExtensions_CreateValidatedPrice_ThrowsOnInvalid()
        {
            // Arrange
            Integration.Test.Price price = -100;  // Implicit conversion

            // Act & Assert
            var exception = Assert.Throws<ArgumentOutOfRangeException>(() => price.CreateValidated());
            Assert.Contains("Price must be greater than or equal to 0", exception.Message);
        }

        [Fact]
        public void ValidationExtensions_CreateValidatedOrderId_ReturnsValueOnValid()
        {
            // Arrange
            Integration.Test.OrderId orderId = 123;  // Implicit conversion

            // Act
            var validatedOrderId = orderId.CreateValidated();

            // Assert
            Assert.Equal(123, validatedOrderId.Value);
        }

        [Fact]
        public void ValidationExtensions_CreateValidatedOrderId_ThrowsOnInvalid()
        {
            // Arrange
            Integration.Test.OrderId orderId = 0;  // Implicit conversion

            // Act & Assert
            var exception = Assert.Throws<ArgumentOutOfRangeException>(() => orderId.CreateValidated());
            Assert.Contains("OrderId must be greater than or equal to 1", exception.Message);
        }
    }
}
