using System;
using System.Runtime.InteropServices;
using Integration.Test.V0;

namespace SbeCodeGenerator.IntegrationTests
{
    /// <summary>
    /// Integration tests that validate the source generator works end-to-end:
    /// - XML schemas are fed via AdditionalFiles
    /// - Code is generated by the SBE source generator
    /// - Generated code compiles successfully
    /// - Generated code can be instantiated and used
    /// These tests ensure the generator output is valid and usable in real scenarios.
    /// </summary>
    public class GeneratorIntegrationTests
    {
        [Fact]
        public void GeneratedCode_CompilesSuccessfully()
        {
            // This test validates that code was generated and compiles by referencing types
            // If the generator didn't work, these types wouldn't exist and the test wouldn't compile
            
            // Verify types from integration-test-schema.xml are generated
            Assert.NotNull(typeof(Integration.Test.V0.OrderSide));
            Assert.NotNull(typeof(Integration.Test.V0.OrderType));
            Assert.NotNull(typeof(Integration.Test.V0.MessageHeader));
            Assert.NotNull(typeof(Integration.Test.V0.NewOrderData));
            Assert.NotNull(typeof(Integration.Test.V0.OrderBookData));
        }

        [Fact]
        public void GeneratedEnum_CanBeUsedInCode()
        {
            // Verify enums can be instantiated and used
            var orderSide = Integration.Test.V0.OrderSide.Buy;
            Assert.Equal((byte)1, (byte)orderSide);
            
            var orderType = Integration.Test.V0.OrderType.Limit;
            Assert.Equal((byte)2, (byte)orderType);
        }

        [Fact]
        public unsafe void GeneratedMessage_CanBeInstantiatedAndAccessed()
        {
            // Verify we can create and access generated message structures
            // Verify the struct has the expected size (calculated based on fields)
            Assert.True(Marshal.SizeOf<Integration.Test.V0.NewOrderData>() > 0);
            
            // Verify we can set and get fields through the generated properties
            Span<byte> buffer = stackalloc byte[1024];
            ref Integration.Test.V0.NewOrderData orderRef = ref MemoryMarshal.AsRef<Integration.Test.V0.NewOrderData>(buffer);
            
            // Use implicit conversions and constructors
            orderRef.OrderId = 123456;  // Implicit conversion from long
            orderRef.Price = 100000;    // Implicit conversion from long
            orderRef.Quantity = 500;
            orderRef.Side = Integration.Test.V0.OrderSide.Buy;
            orderRef.OrderType = Integration.Test.V0.OrderType.Limit;
            
            Assert.Equal(123456, orderRef.OrderId.Value);
            Assert.Equal(100000, orderRef.Price.Value);
            Assert.Equal(500, orderRef.Quantity);
            Assert.Equal(Integration.Test.V0.OrderSide.Buy, orderRef.Side);
            Assert.Equal(Integration.Test.V0.OrderType.Limit, orderRef.OrderType);
        }

        [Fact]
        public unsafe void GeneratedMessageHeader_HasCorrectStructure()
        {
            // Verify MessageHeader composite is generated correctly
            Span<byte> buffer = stackalloc byte[128];
            ref Integration.Test.V0.MessageHeader header = ref MemoryMarshal.AsRef<Integration.Test.V0.MessageHeader>(buffer);
            
            header.BlockLength = 100;
            header.TemplateId = 10;
            header.SchemaId = 2;
            header.Version = 0;
            
            Assert.Equal((ushort)100, header.BlockLength);
            Assert.Equal((ushort)10, header.TemplateId);
            Assert.Equal((ushort)2, header.SchemaId);
            Assert.Equal((ushort)0, header.Version);
        }


        [Fact]
        public void GeneratedMessage_TryParseReturnsStructCopy()
        {
            // Prepare a buffer with the raw bytes of NewOrderData
            Span<byte> buffer = stackalloc byte[Integration.Test.V0.NewOrderData.MESSAGE_SIZE];
            ref Integration.Test.V0.NewOrderData orderRef = ref MemoryMarshal.AsRef<Integration.Test.V0.NewOrderData>(buffer);
            orderRef.OrderId = 999;      // Implicit conversion
            orderRef.Price = 50000;      // Implicit conversion
            orderRef.Quantity = 100;
            orderRef.Side = Integration.Test.V0.OrderSide.Sell;
            orderRef.OrderType = Integration.Test.V0.OrderType.Market;

            // Act
            var success = Integration.Test.V0.NewOrderData.TryParse(buffer, out var parsedOrder);

            // Assert
            Assert.True(success);
            Assert.Equal(0, buffer.Length - Integration.Test.V0.NewOrderData.MESSAGE_SIZE);
            Assert.Equal(999, parsedOrder.Data.OrderId.Value);
            Assert.Equal(50000, parsedOrder.Data.Price.Value);
            Assert.Equal(100, parsedOrder.Data.Quantity);
            Assert.Equal(Integration.Test.V0.OrderSide.Sell, parsedOrder.Data.Side);
            Assert.Equal(Integration.Test.V0.OrderType.Market, parsedOrder.Data.OrderType);
        }

        [Fact]
        public void GeneratedMessageHeader_TryParseExposesPayload()
        {
            Span<byte> buffer = stackalloc byte[Integration.Test.V0.MessageHeader.MESSAGE_SIZE + Integration.Test.V0.NewOrderData.MESSAGE_SIZE];
            var bodyOffset = Integration.Test.V0.MessageHeader.MESSAGE_SIZE;
            ref Integration.Test.V0.MessageHeader header = ref MemoryMarshal.AsRef<Integration.Test.V0.MessageHeader>(buffer);
            header.BlockLength = (ushort)Integration.Test.V0.NewOrderData.MESSAGE_SIZE;
            header.TemplateId = (ushort)Integration.Test.V0.NewOrderData.MESSAGE_ID;
            header.SchemaId = 2;
            header.Version = 0;
            ref Integration.Test.V0.NewOrderData order = ref MemoryMarshal.AsRef<Integration.Test.V0.NewOrderData>(buffer.Slice(bodyOffset));
            order.OrderId = 42;  // Implicit conversion

            var success = Integration.Test.V0.MessageHeader.TryParse(buffer, out var parsedHeader, out var payload);

            Assert.True(success);
            Assert.Equal(Integration.Test.V0.NewOrderData.MESSAGE_ID, parsedHeader.TemplateId);
            Assert.Equal(Integration.Test.V0.NewOrderData.MESSAGE_SIZE, parsedHeader.BlockLength);
            Assert.Equal(Integration.Test.V0.NewOrderData.MESSAGE_SIZE, payload.Length);
            Assert.Equal(42, MemoryMarshal.AsRef<Integration.Test.V0.NewOrderData>(payload).OrderId.Value);
        }

        [Fact]
        public void GeneratedCode_HasCorrectNamespaces()
        {
            // Verify namespace generation from file names
            // integration-test-schema.xml -> Integration.Test
            Assert.Equal("Integration.Test.V0", typeof(Integration.Test.V0.OrderSide).Namespace);
        }

        [Fact]
        public void WriteHeader_PopulatesHeaderCorrectly()
        {
            Span<byte> buffer = stackalloc byte[Integration.Test.V0.MessageHeader.MESSAGE_SIZE + Integration.Test.V0.NewOrderData.MESSAGE_SIZE];

            var headerSize = Integration.Test.V0.NewOrderData.WriteHeader(buffer);
            ref var header = ref MemoryMarshal.AsRef<Integration.Test.V0.MessageHeader>(buffer);

            Assert.Equal(Integration.Test.V0.MessageHeader.MESSAGE_SIZE, headerSize);
            Assert.Equal((ushort)Integration.Test.V0.NewOrderData.BLOCK_LENGTH, header.BlockLength);
            Assert.Equal((ushort)Integration.Test.V0.NewOrderData.MESSAGE_ID, header.TemplateId);
            Assert.Equal((ushort)2, header.SchemaId);
            Assert.Equal((ushort)0, header.Version);
        }

        [Fact]
        public unsafe void GeneratedMessageWithGroups_CanBeAccessed()
        {
            // Verify messages with groups are generated (OrderBook has bids/asks groups)
            Assert.True(Marshal.SizeOf<Integration.Test.V0.OrderBookData>() > 0);
            
            Span<byte> buffer = stackalloc byte[1024];
            ref Integration.Test.V0.OrderBookData bookRef = ref MemoryMarshal.AsRef<Integration.Test.V0.OrderBookData>(buffer);
            
            bookRef.InstrumentId = 42;
            Assert.Equal(42, bookRef.InstrumentId);
        }

        [Fact]
        public void BlockLengthExtension_AllowsDifferentBlockLengths()
        {
            // Test the new TryParse overload that accepts a blockLength parameter
            // This is the foundation for schema evolution support
            
            Span<byte> buffer = stackalloc byte[Integration.Test.V0.NewOrderData.MESSAGE_SIZE + 32]; // Extra space
            ref Integration.Test.V0.NewOrderData message = ref MemoryMarshal.AsRef<Integration.Test.V0.NewOrderData>(buffer);
            
            message.OrderId = 123;    // Implicit conversion
            message.Price = 9950;     // Implicit conversion
            message.Quantity = 100;
            message.Side = Integration.Test.V0.OrderSide.Buy;
            message.OrderType = Integration.Test.V0.OrderType.Limit;
            
            // Test with exact block length (standard case)
            var success1 = Integration.Test.V0.NewOrderData.TryParse(
                buffer, 
                Integration.Test.V0.NewOrderData.MESSAGE_SIZE, 
                out var parsedMsg1);
            
            Assert.True(success1);
            Assert.Equal(123, parsedMsg1.Data.OrderId.Value);
            Assert.Equal(32, buffer.Length - Integration.Test.V0.NewOrderData.MESSAGE_SIZE); // 32 bytes remain for variable data
            
            // Test with larger block length (simulates newer schema with additional fields)
            int extendedBlockLength = Integration.Test.V0.NewOrderData.MESSAGE_SIZE + 16;
            var success2 = Integration.Test.V0.NewOrderData.TryParse(
                buffer, 
                extendedBlockLength, 
                out var parsedMsg2);
            
            Assert.True(success2);
            Assert.Equal(123, parsedMsg2.Data.OrderId.Value);
            Assert.Equal(16, buffer.Length - extendedBlockLength); // 16 bytes remain for variable data
            
            // Test with smaller block length (simulates older schema with fewer fields)
            int smallerBlockLength = Integration.Test.V0.NewOrderData.MESSAGE_SIZE - 2;
            var success3 = Integration.Test.V0.NewOrderData.TryParse(
                buffer, 
                smallerBlockLength, 
                out var parsedMsg3);
            
            Assert.True(success3);
            Assert.Equal(123, parsedMsg3.Data.OrderId.Value);
            Assert.Equal(34, buffer.Length - smallerBlockLength); // More bytes remain
        }

        [Fact]
        public void BlockLengthExtension_BackwardCompatibleTryParse()
        {
            // Verify that the original TryParse (without blockLength) still works
            // This ensures backward compatibility with existing code
            
            Span<byte> buffer = stackalloc byte[Integration.Test.V0.NewOrderData.MESSAGE_SIZE];
            ref Integration.Test.V0.NewOrderData message = ref MemoryMarshal.AsRef<Integration.Test.V0.NewOrderData>(buffer);
            
            message.OrderId = 456;    // Implicit conversion
            message.Price = 10050;    // Implicit conversion
            
            // Use the original TryParse method (calls the new one internally with MESSAGE_SIZE)
            var success = Integration.Test.V0.NewOrderData.TryParse(buffer, out var parsedMsg);
            
            Assert.True(success);
            Assert.Equal(456, parsedMsg.Data.OrderId.Value);
            Assert.Equal(10050, parsedMsg.Data.Price.Value);
            Assert.Equal(0, buffer.Length - Integration.Test.V0.NewOrderData.MESSAGE_SIZE);
        }

        [Fact]
        public void ValidationExtensions_ValidatePrice_ThrowsOnNegativeValue()
        {
            // Arrange
            Integration.Test.V0.Price price = -100;  // Implicit conversion

            // Act & Assert
            var exception = Assert.Throws<ArgumentOutOfRangeException>(() => price.Validate());
            Assert.Contains("Price must be greater than or equal to 0", exception.Message);
        }

        [Fact]
        public void ValidationExtensions_ValidatePrice_PassesOnValidValue()
        {
            // Arrange
            Integration.Test.V0.Price price = 1000;  // Implicit conversion

            // Act & Assert (should not throw)
            price.Validate();
        }

        [Fact]
        public void ValidationExtensions_ValidateOrderId_ThrowsOnZeroValue()
        {
            // Arrange
            Integration.Test.V0.OrderId orderId = 0;  // Implicit conversion

            // Act & Assert
            var exception = Assert.Throws<ArgumentOutOfRangeException>(() => orderId.Validate());
            Assert.Contains("OrderId must be greater than or equal to 1", exception.Message);
        }

        [Fact]
        public void ValidationExtensions_ValidateOrderId_PassesOnValidValue()
        {
            // Arrange
            Integration.Test.V0.OrderId orderId = 123;  // Implicit conversion

            // Act & Assert (should not throw)
            orderId.Validate();
        }

        [Fact]
        public void ValidationExtensions_TryValidatePrice_ReturnsFalseOnNegativeValue()
        {
            // Arrange
            Integration.Test.V0.Price price = -100;  // Implicit conversion

            // Act
            bool result = price.TryValidate(out string? errorMessage);

            // Assert
            Assert.False(result);
            Assert.NotNull(errorMessage);
            Assert.Contains("Price must be greater than or equal to 0", errorMessage);
            Assert.Contains("-100", errorMessage);
        }

        [Fact]
        public void ValidationExtensions_TryValidatePrice_ReturnsTrueOnValidValue()
        {
            // Arrange
            Integration.Test.V0.Price price = 1000;  // Implicit conversion

            // Act
            bool result = price.TryValidate(out string? errorMessage);

            // Assert
            Assert.True(result);
            Assert.Null(errorMessage);
        }

        [Fact]
        public void ValidationExtensions_TryValidateOrderId_ReturnsFalseOnZeroValue()
        {
            // Arrange
            Integration.Test.V0.OrderId orderId = 0;  // Implicit conversion

            // Act
            bool result = orderId.TryValidate(out string? errorMessage);

            // Assert
            Assert.False(result);
            Assert.NotNull(errorMessage);
            Assert.Contains("OrderId must be greater than or equal to 1", errorMessage);
        }

        [Fact]
        public void ValidationExtensions_CreateValidatedPrice_ReturnsValueOnValid()
        {
            // Arrange
            Integration.Test.V0.Price price = 1000;  // Implicit conversion

            // Act
            var validatedPrice = price.CreateValidated();

            // Assert
            Assert.Equal(1000, validatedPrice.Value);
        }

        [Fact]
        public void ValidationExtensions_CreateValidatedPrice_ThrowsOnInvalid()
        {
            // Arrange
            Integration.Test.V0.Price price = -100;  // Implicit conversion

            // Act & Assert
            var exception = Assert.Throws<ArgumentOutOfRangeException>(() => price.CreateValidated());
            Assert.Contains("Price must be greater than or equal to 0", exception.Message);
        }

        [Fact]
        public void ValidationExtensions_CreateValidatedOrderId_ReturnsValueOnValid()
        {
            // Arrange
            Integration.Test.V0.OrderId orderId = 123;  // Implicit conversion

            // Act
            var validatedOrderId = orderId.CreateValidated();

            // Assert
            Assert.Equal(123, validatedOrderId.Value);
        }

        [Fact]
        public void ValidationExtensions_CreateValidatedOrderId_ThrowsOnInvalid()
        {
            // Arrange
            Integration.Test.V0.OrderId orderId = 0;  // Implicit conversion

            // Act & Assert
            var exception = Assert.Throws<ArgumentOutOfRangeException>(() => orderId.CreateValidated());
            Assert.Contains("OrderId must be greater than or equal to 1", exception.Message);
        }

        [Fact]
        public void ConsumeVariableLengthSegments_WithSpanReader_ParsesGroupsCorrectly()
        {
            // Arrange - Create buffer with OrderBookData fixed fields + GroupSizeEncoding + entries for bids and asks
            Span<byte> buffer = stackalloc byte[512];
            int offset = 0;
            
            // Reserve space for OrderBookData fixed fields
            offset += Integration.Test.V0.OrderBookData.MESSAGE_SIZE;
            
            // Write bids group header (3 bids)
            ref Integration.Test.V0.GroupSizeEncoding bidsHeader = ref MemoryMarshal.AsRef<Integration.Test.V0.GroupSizeEncoding>(buffer.Slice(offset));
            bidsHeader.BlockLength = (ushort)Integration.Test.V0.OrderBookData.BidsData.MESSAGE_SIZE;
            bidsHeader.NumInGroup = 3;
            offset += Integration.Test.V0.GroupSizeEncoding.MESSAGE_SIZE;
            
            // Write bid entries
            for (int i = 0; i < 3; i++)
            {
                ref Integration.Test.V0.OrderBookData.BidsData bid = ref MemoryMarshal.AsRef<Integration.Test.V0.OrderBookData.BidsData>(buffer.Slice(offset));
                bid.Price = 1000 + i * 10;  // Implicit conversion
                bid.Quantity = 100 + i;
                offset += Integration.Test.V0.OrderBookData.BidsData.MESSAGE_SIZE;
            }
            
            // Write asks group header (2 asks)
            ref Integration.Test.V0.GroupSizeEncoding asksHeader = ref MemoryMarshal.AsRef<Integration.Test.V0.GroupSizeEncoding>(buffer.Slice(offset));
            asksHeader.BlockLength = (ushort)Integration.Test.V0.OrderBookData.AsksData.MESSAGE_SIZE;
            asksHeader.NumInGroup = 2;
            offset += Integration.Test.V0.GroupSizeEncoding.MESSAGE_SIZE;
            
            // Write ask entries
            for (int i = 0; i < 2; i++)
            {
                ref Integration.Test.V0.OrderBookData.AsksData ask = ref MemoryMarshal.AsRef<Integration.Test.V0.OrderBookData.AsksData>(buffer.Slice(offset));
                ask.Price = 2000 + i * 10;  // Implicit conversion
                ask.Quantity = 200 + i;
                offset += Integration.Test.V0.OrderBookData.AsksData.MESSAGE_SIZE;
            }
            
            // Act
            var bidPrices = new System.Collections.Generic.List<long>();
            var askPrices = new System.Collections.Generic.List<long>();
            var bidQuantities = new System.Collections.Generic.List<long>();
            var askQuantities = new System.Collections.Generic.List<long>();
            
            // Parse using TryParse and call ReadGroups
            Assert.True(Integration.Test.V0.OrderBookData.TryParse(buffer.Slice(0, offset), out var orderBookReader));
            orderBookReader.ReadGroups(
                (in Integration.Test.V0.OrderBookData.BidsData bid) => { bidPrices.Add(bid.Price.Value); bidQuantities.Add(bid.Quantity); },
                (in Integration.Test.V0.OrderBookData.AsksData ask) => { askPrices.Add(ask.Price.Value); askQuantities.Add(ask.Quantity); }
            );
            
            // Assert
            Assert.Equal(3, bidPrices.Count);
            Assert.Equal(2, askPrices.Count);
            
            // Verify bids
            Assert.Equal(1000, bidPrices[0]);
            Assert.Equal(1010, bidPrices[1]);
            Assert.Equal(1020, bidPrices[2]);
            Assert.Equal(100, bidQuantities[0]);
            Assert.Equal(101, bidQuantities[1]);
            Assert.Equal(102, bidQuantities[2]);
            
            // Verify asks
            Assert.Equal(2000, askPrices[0]);
            Assert.Equal(2010, askPrices[1]);
            Assert.Equal(200, askQuantities[0]);
            Assert.Equal(201, askQuantities[1]);
        }

        [Fact]
        public void ConsumeVariableLengthSegments_WithSpanReader_ParsesDataFieldsCorrectly()
        {
            // Arrange - Create buffer with NewOrderData fixed fields + VarString8 data
            Span<byte> buffer = stackalloc byte[512];
            int offset = 0;
            
            // Reserve space for NewOrderData fixed fields
            offset += Integration.Test.V0.NewOrderData.MESSAGE_SIZE;
            
            // Write VarString8: length byte + string bytes
            string testSymbol = "AAPL";
            buffer[offset++] = (byte)testSymbol.Length;
            for (int i = 0; i < testSymbol.Length; i++)
            {
                buffer[offset++] = (byte)testSymbol[i];
            }
            
            // Act
            byte symbolLength = 0;
            string symbolStr = "";
            Assert.True(Integration.Test.V0.NewOrderData.TryParse(buffer.Slice(0, offset), out var orderReader));
            orderReader.ReadGroups(
                symbol => { 
                    symbolLength = symbol.Length;
                    symbolStr = System.Text.Encoding.UTF8.GetString(symbol.VarData);
                }
            );
            
            // Assert
            Assert.Equal((byte)4, symbolLength);
            Assert.Equal("AAPL", symbolStr);
        }

        [Fact]
        public void TryParse_WithSpanReader_ValidatesBufferLength()
        {
            // Test that TryParse using SpanReader properly validates buffer length
            // This ensures CanRead check works correctly
            
            // Arrange - Create a buffer that's too small
            Span<byte> smallBuffer = stackalloc byte[10]; // Less than MESSAGE_SIZE (26)
            
            // Act
            var success = Integration.Test.V0.NewOrderData.TryParse(smallBuffer, out var reader);
            
            // Assert
            Assert.False(success);
        }

        [Fact]
        public void TryParse_WithSpanReader_ReadsMessageCorrectly()
        {
            // Test that TryParse using SpanReader reads the message struct correctly
            
            // Arrange
            Span<byte> buffer = stackalloc byte[Integration.Test.V0.NewOrderData.MESSAGE_SIZE + 16];
            ref Integration.Test.V0.NewOrderData orderRef = ref MemoryMarshal.AsRef<Integration.Test.V0.NewOrderData>(buffer);
            orderRef.OrderId = 12345;    // Implicit conversion
            orderRef.Price = 99999;      // Implicit conversion
            orderRef.Quantity = 500;
            orderRef.Side = Integration.Test.V0.OrderSide.Buy;
            orderRef.OrderType = Integration.Test.V0.OrderType.Limit;
            
            // Act
            var success = Integration.Test.V0.NewOrderData.TryParse(buffer, out var message);
            
            // Assert
            Assert.True(success);
            Assert.Equal(12345, message.Data.OrderId.Value);
            Assert.Equal(99999, message.Data.Price.Value);
            Assert.Equal(500, message.Data.Quantity);
            Assert.Equal(Integration.Test.V0.OrderSide.Buy, message.Data.Side);
            Assert.Equal(Integration.Test.V0.OrderType.Limit, message.Data.OrderType);
            Assert.Equal(16, buffer.Length - Integration.Test.V0.NewOrderData.MESSAGE_SIZE); // Remaining bytes after MESSAGE_SIZE
        }

        [Fact]
        public void TryParse_WithSpanReader_HandlesSchemaEvolutionWithLargerBlockLength()
        {
            // Test that TryParse using SpanReader correctly skips additional bytes
            // when blockLength > MESSAGE_SIZE (newer schema version)
            
            // Arrange
            int extendedBlockLength = Integration.Test.V0.NewOrderData.MESSAGE_SIZE + 8;
            Span<byte> buffer = stackalloc byte[extendedBlockLength + 10]; // Extra space for variable data
            ref Integration.Test.V0.NewOrderData orderRef = ref MemoryMarshal.AsRef<Integration.Test.V0.NewOrderData>(buffer);
            orderRef.OrderId = 777;
            orderRef.Price = 5000;
            
            // Act - Parse with larger block length
            var success = Integration.Test.V0.NewOrderData.TryParse(buffer, extendedBlockLength, out var message);
            
            // Assert
            Assert.True(success);
            Assert.Equal(777, message.Data.OrderId.Value);
            Assert.Equal(5000, message.Data.Price.Value);
            // Variable data should start after the extended block length
            Assert.Equal(10, buffer.Length - extendedBlockLength);
        }

        [Fact]
        public void TryParse_WithSpanReader_HandlesSchemaEvolutionWithSmallerBlockLength()
        {
            // Test that TryParse using SpanReader correctly handles older schema versions
            // when blockLength < MESSAGE_SIZE
            
            // Arrange
            int smallerBlockLength = Integration.Test.V0.NewOrderData.MESSAGE_SIZE - 4;
            Span<byte> buffer = stackalloc byte[Integration.Test.V0.NewOrderData.MESSAGE_SIZE + 20];
            ref Integration.Test.V0.NewOrderData orderRef = ref MemoryMarshal.AsRef<Integration.Test.V0.NewOrderData>(buffer);
            orderRef.OrderId = 888;
            orderRef.Price = 6000;
            
            // Act - Parse with smaller block length
            var success = Integration.Test.V0.NewOrderData.TryParse(buffer, smallerBlockLength, out var message);
            
            // Assert
            Assert.True(success);
            Assert.Equal(888, message.Data.OrderId.Value);
            Assert.Equal(6000, message.Data.Price.Value);
            // Variable data should start at smallerBlockLength, overlapping with message
            Assert.Equal(Integration.Test.V0.NewOrderData.MESSAGE_SIZE + 20 - smallerBlockLength, buffer.Length - smallerBlockLength);
        }

        [Fact]
        public void TryParse_WithSpanReader_FailsWhenInsufficientBufferForBlockLength()
        {
            // Test that TryParse fails when buffer is smaller than blockLength
            // This validates the CanRead check in SpanReader
            
            // Arrange
            int blockLength = 50;
            Span<byte> buffer = stackalloc byte[40]; // Less than blockLength
            
            // Act
            var success = Integration.Test.V0.NewOrderData.TryParse(buffer, blockLength, out var reader);
            
            // Assert
            Assert.False(success);
        }

        [Fact]
        public void TryParse_WithSpanReader_FailsWhenInsufficientBufferForMessage()
        {
            // Test that TryParse fails when buffer is smaller than blockLength
            // This validates the TryReadBlock check in SpanReader
            
            // Arrange - blockLength larger than available buffer
            int blockLength = 20;
            Span<byte> buffer = stackalloc byte[10]; // Less than blockLength
            
            // Act
            var success = Integration.Test.V0.NewOrderData.TryParse(buffer, blockLength, out var reader);
            
            // Assert - should fail because buffer is too small for blockLength
            Assert.False(success);
            
            // Verify that blockLength < MESSAGE_SIZE succeeds (backward compat: partial read)
            int smallBlockLength = 10;
            Span<byte> adequateBuffer = stackalloc byte[10];
            var partialSuccess = Integration.Test.V0.NewOrderData.TryParse(adequateBuffer, smallBlockLength, out var partialReader);
            Assert.True(partialSuccess);
        }

        [Fact]
        public void ConsumeVariableLengthSegments_WithRefSpanReader_ParsesGroupsCorrectly()
        {
            // Test that ReadGroups correctly parses groups from the buffer
            // Arrange - Create buffer with OrderBookData fixed fields + GroupSizeEncoding + entries for bids and asks
            Span<byte> buffer = stackalloc byte[512];
            int offset = 0;
            
            // Reserve space for OrderBookData fixed fields
            offset += Integration.Test.V0.OrderBookData.MESSAGE_SIZE;
            
            // Write bids group header (3 bids)
            ref Integration.Test.V0.GroupSizeEncoding bidsHeader = ref MemoryMarshal.AsRef<Integration.Test.V0.GroupSizeEncoding>(buffer.Slice(offset));
            bidsHeader.BlockLength = (ushort)Integration.Test.V0.OrderBookData.BidsData.MESSAGE_SIZE;
            bidsHeader.NumInGroup = 3;
            offset += Integration.Test.V0.GroupSizeEncoding.MESSAGE_SIZE;
            
            // Write bid entries
            for (int i = 0; i < 3; i++)
            {
                ref Integration.Test.V0.OrderBookData.BidsData bid = ref MemoryMarshal.AsRef<Integration.Test.V0.OrderBookData.BidsData>(buffer.Slice(offset));
                bid.Price = 1000 + i * 10;  // Implicit conversion
                bid.Quantity = 100 + i;
                offset += Integration.Test.V0.OrderBookData.BidsData.MESSAGE_SIZE;
            }
            
            // Write asks group header (2 asks)
            ref Integration.Test.V0.GroupSizeEncoding asksHeader = ref MemoryMarshal.AsRef<Integration.Test.V0.GroupSizeEncoding>(buffer.Slice(offset));
            asksHeader.BlockLength = (ushort)Integration.Test.V0.OrderBookData.AsksData.MESSAGE_SIZE;
            asksHeader.NumInGroup = 2;
            offset += Integration.Test.V0.GroupSizeEncoding.MESSAGE_SIZE;
            
            // Write ask entries
            for (int i = 0; i < 2; i++)
            {
                ref Integration.Test.V0.OrderBookData.AsksData ask = ref MemoryMarshal.AsRef<Integration.Test.V0.OrderBookData.AsksData>(buffer.Slice(offset));
                ask.Price = 2000 + i * 10;  // Implicit conversion
                ask.Quantity = 200 + i;
                offset += Integration.Test.V0.OrderBookData.AsksData.MESSAGE_SIZE;
            }
            
            // Add extra data after the variable length segments
            buffer[offset++] = 0xFF;
            buffer[offset++] = 0xAA;
            
            // Act
            var bidPrices = new System.Collections.Generic.List<long>();
            var askPrices = new System.Collections.Generic.List<long>();
            var bidQuantities = new System.Collections.Generic.List<long>();
            var askQuantities = new System.Collections.Generic.List<long>();
            
            // Parse using TryParse and call ReadGroups
            Assert.True(Integration.Test.V0.OrderBookData.TryParse(buffer.Slice(0, offset), out var orderBookReader));
            orderBookReader.ReadGroups(
                (in Integration.Test.V0.OrderBookData.BidsData bid) => { bidPrices.Add(bid.Price.Value); bidQuantities.Add(bid.Quantity); },
                (in Integration.Test.V0.OrderBookData.AsksData ask) => { askPrices.Add(ask.Price.Value); askQuantities.Add(ask.Quantity); }
            );
            
            // Assert - Verify parsed data
            Assert.Equal(3, bidPrices.Count);
            Assert.Equal(2, askPrices.Count);
            
            // Verify bids
            Assert.Equal(1000, bidPrices[0]);
            Assert.Equal(1010, bidPrices[1]);
            Assert.Equal(1020, bidPrices[2]);
            Assert.Equal(100, bidQuantities[0]);
            Assert.Equal(101, bidQuantities[1]);
            Assert.Equal(102, bidQuantities[2]);
            
            // Verify asks
            Assert.Equal(2000, askPrices[0]);
            Assert.Equal(2010, askPrices[1]);
            Assert.Equal(200, askQuantities[0]);
            Assert.Equal(201, askQuantities[1]);
        }

        [Fact]
        public void ConsumeVariableLengthSegments_WithRefSpanReader_ParsesDataFieldsCorrectly()
        {
            // Test that ReadGroups works with data fields
            
            // Arrange - Create buffer with NewOrderData fixed fields + VarString8 data
            Span<byte> buffer = stackalloc byte[512];
            int offset = 0;
            
            // Reserve space for NewOrderData fixed fields
            offset += Integration.Test.V0.NewOrderData.MESSAGE_SIZE;
            
            // Write VarString8: length byte + string bytes
            string testSymbol = "AAPL";
            buffer[offset++] = (byte)testSymbol.Length;
            for (int i = 0; i < testSymbol.Length; i++)
            {
                buffer[offset++] = (byte)testSymbol[i];
            }
            
            // Act
            byte symbolLength = 0;
            string symbolStr = "";
            Assert.True(Integration.Test.V0.NewOrderData.TryParse(buffer.Slice(0, offset), out var orderReader));
            orderReader.ReadGroups(
                symbol => { 
                    symbolLength = symbol.Length;
                    symbolStr = System.Text.Encoding.UTF8.GetString(symbol.VarData);
                }
            );
            
            // Assert
            Assert.Equal((byte)4, symbolLength);
            Assert.Equal("AAPL", symbolStr);
        }
    }
}
